### ISSUE TITLE
Create bottom navigation 

### ISSUE THREAD

**Issue by isabelcshaw** [OpenSRP/opensrp-client-tasking#22]
At the bottom of the app, there will be a constant navigation bar. This bar allows the user to move between four different pages: 

1. "My Tasks" --> the prioritized task list view 
2. "My Clients" --> client register 
3. "My Performance" --> performance dashboard 
4. "Training" --> for v1, this will not go anywhere

Each will also show an icon. When the user is on one of the pages, the component of the menu will turn blue. 

Image from the mocks here: 
<img width="299" alt="Screen Shot 2020-08-05 at 4 27 48 PM" src="https://user-images.githubusercontent.com/12836913/89473789-9ff51180-d738-11ea-8f3b-6abb8341ba71.png">

**Comment by allan-allay** [comment]
We'll not have this view in the app. It's been removed in subsequent Goldsmith UI designs by Roger.
