### ISSUE TITLE
Pull in client register for "My Clients" view 

### ISSUE THREAD

**Issue by isabelcshaw** [OpenSRP/opensrp-client-tasking#23]
The "My Clients" view will bring the user to the CHW client register. 

For this, we will need to pull in the existing all families roster. The expected functionality here should be the same as any other CHW app. The user can click on a family in the roster and enter the family module, where they can view individual members of the family. 

This work should also include pulling over the ability to add a new family, search, and sort this roster. 

<img width="299" alt="Screen Shot 2020-08-05 at 11 12 51 PM" src="https://user-images.githubusercontent.com/12836913/89497435-36ddc000-d771-11ea-8bb9-769ab679f88c.png">

**Comment by allan-allay** [comment]
Duplicated and updated in https://github.com/OpenSRP/opensrp-client-goldsmith/issues/6
